---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: Test-Deployment-CR
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Test-Deployment-CR
      version: 54
  template:
    metadata:
      labels:
        app: Test-Deployment-CR-MVN
        version: 54
    spec:
      containers:
        - name: Test-Deployment-CR
          image: image-repo:image-tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    app: Test-Deployment-CR-MVN-SVC
spec:
  selector:
    app: Test-Deployment-CR-MVN
    version: 54
  type: NodePort
  ports:
    - nodePort: 85
      protocol: TCP
      port: 8080
      targetPort: 8080