# Creating Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  namespace: deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      namespace: deployment
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "$Kuber_Secret"



# Creating ClusterIP Services
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: True
  labels:
    app: petclinic
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  externalIPs:
    - 172.31.6.52

##ConfigMap for nginx
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  namespace: deployment
#  name: nginx-config
#data:
#
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-ingress
#  namespace: deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: nginx-ingress
#  template:
#    metadata:
#      labels:
#        app: nginx-ingress
#    spec:
#      containers:
#        - image: nginx/nginx-ingress:edge
#          imagePullPolicy: Always
#          name: nginx-ingress
#          ports:
#            - name: http
#              containerPort: 80
#          env:
#            - name: POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#          args:
#            - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: petclinic
  externalIPs:
    - 3.239.33.115