## Creating Namespace
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "$Kuber_Secret"



# Creating ClusterIP Services

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30718
  externalIPs:
    - 3.239.33.116
  selector:
    app: petclinic

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              servicePort: 30718
              serviceName: test
            path: /maven-test