## Creating Namespace
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
#  namespace: deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
#      namespace: deployment
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "$Kuber_Secret"



# Creating ClusterIP Services

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
#  namespace: deployment
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30718
  selector:
    app: petclinic
  externalIPs:
    - 3.239.33.115

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
spec:
  rules:
    - host: 34.232.95.97
      http:
        paths:
          - path: /petclinic
            backend:
              serviceName: petclinic-nodeport
              servicePort: 30718

