---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Test-Deployment-CR
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Test-Deployment-CR
      version: blue
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: Test-Deployment-CR-MVN
        version: blue
    spec:
      containers:
        - name: Test-Deployment-CR
          image: 315727832121.dkr.ecr.us-east-1.amazonaws.com/maven-cruntov:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    app: test-app
spec:
  selector:
    app: Test-Deployment-CR-MVN
    version: blue
  type: NodePort
  ports:
    - nodePort: 31113
      port: 80
      targetPort: 8080