---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          env:
            - name: MYSQL_USER
              value: runtov
            - name: MYSQL_PASS
              value: 21AJjEQE9yToMrAa
            - name: MYSQL_URL
              value: 172.31.6.246:3306/runtov
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 3306
              name: mysql
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            timeoutSeconds: 30
      imagePullSecrets:
        - name: "$Kuber_Secret"


---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
    - nodePort: 30718
      protocol: TCP
      port: 80
      targetPort: 8080


