apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "var:$Docker_Registry/var:$ECR_Repository:var:$GIT_COMMIT"
          name: petclinic
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "var:$Kuber_Secret"



---
#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-service
#spec:
#  selector:
#    app: petclinic
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 30008
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: True
  labels:
    app: petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
