#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: aurora
#spec:
#  type: ExternalName
#  externalName: aurora-cluster-internship.cluster-cpct4armoank.us-east-1.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: external-mysql
spec:
  clusterIP: None
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0
  selector: {}

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-mysql
subsets:
  - addresses:
      - ip: 172.31.6.246
  - ports:
      - port: 3306
        name: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          env:
            - name: MYSQL_USER
              value: runtov
            - name: MYSQL_PASS
              value: 21AJjEQE9yToMrAa
            - name: MYSQL_URL
              value: aurora-cluster-internship.cluster-cpct4armoank.us-east-1.rds.amazonaws.com:3306/runtov
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 3306
              name: mysql
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "$Kuber_Secret"



# Creating ClusterIP Services
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
    - nodePort: 30718
      protocol: TCP
      port: 80
      targetPort: 8080
  externalTrafficPolicy: Local


