---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      name: petclinic
    spec:
      containers:
        - image: image-repo:image-tag
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
#              hostPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "ecr-cruntov-creds"


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: "petclinic"
  name: "petclinic"
  namespace: "default"
spec:
#  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32640
      targetPort: 8080
  externalIPs:
    - "127.0.0.1"
  type: "NodePort"
#  loadBalancerIP: "192.168.15.123"
  selector:
    app: petclinic
#  sessionAffinity: None
