---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: image-repo:image-tag
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: "ecr_creds"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  ports:
    - nodePort: 30123
      port: 8080
      targetPort: 8080
  selector:
    app: petclinic
  type: NodePort