---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: image-repo:image-tag
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
      imagePullSecrets:
        - name: "ecr-cruntov-creds"


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: "petclinic-mvn"
  name: "petclinic-mvn"
  namespace: "default"
spec:
  externalTrafficPolicy: Local
  ports:
    - nodePort: 32640
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  externalIPs:
    - "192.168.15.123"
  type: "NodePort"
#  loadBalancerIP: "192.168.15.123"
  selector:
    app: "petclinic"
  sessionAffinity: None
