---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: library/nginx:latest
          imagePullPolicy: Always
          name: myweb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: myweb
spec:
  ports:
    - nodePort: 32223
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: petclinic
  type: NodePort