---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: image-repo:image-tag
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: "ecr-cruntov-creds"

#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: petclinic
#  name: petclinic-mvn
#spec:
#  ports:
#    - nodePort: 30123
#      port: 8080
#      targetPort: 8080
#      protocol: TCP
#      appProtocol: TCP
#  externalIPs:
#    - "192.168.3.65"
#  selector:
#    app: petclinic
#  type: NodePort
#
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  selector:
    app: petclinic
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer