---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          env:
            - name: MYSQL_USER
              value: $SQL_USER
            - name: MYSQL_PASS
              value: $SQL_PASS
            - name: MYSQL_URL
              value: $SQL_URL
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 3306
              name: mysql
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            timeoutSeconds: 30
      imagePullSecrets:
        - name: "$Kuber_Secret"


---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-nodeport
spec:
  selector:
    app: petclinic
  type: ClusterIP
  ports:
    - nodePort: 30718
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /petclinic(/|$)(.*)
            backend:
              service:
                name: petclinic-nodeport
                port:
                  number: 80
    - host: ec2-3-237-78-242.compute-1.amazonaws.com
