---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: image-repo:image-tag
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic-mvn
spec:
  ports:
    - nodePort: 80
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: petclinic
  type: NodePort