###########################################
#             App Deployment              #
###########################################

# PetClinic App
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mvn
  namespace: $Kuber_Namespace
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: "$Docker_Registry/$ECR_Repository:$GIT_COMMIT"
          name: petclinic
          env:
            - name: MYSQL_USER
              value: $SQL_USER
            - name: MYSQL_PASS
              value: $SQL_PASS
            - name: MYSQL_URL
              value: $SQL_URL
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 3306
              name: mysql
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            timeoutSeconds: 30
      imagePullSecrets:
        - name: "$Kuber_Secret"

# Petclinic Service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: i-06eb145ccd09cfed8
  name: petclinic-nodeport
  namespace: $Kuber_Namespace
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
    - nodePort: 30718
      protocol: TCP
      port: 8080
      targetPort: 8080
